image:
  abs-tmp-path: /home/work/storage
  web-img-path: forum/imge/
  tmp-upload-path: /tmp/forum/
  oss:
    type: local
    endpoint:
    prefix: intelliforum/
    ak:
    sk:
    bucket:
    host: